In [ ]:
!pip install numpy

In [41]:
import numpy as np
ms1 = np.array([1,2,3,4,5,6])  # одномерный массив
ms2 = np.array([[1,2,3,4],[5,6,7,8]])  # двумерный массив
print("Одномерный массив", ms1.dtype)
print("ms1 shape:", ms1.shape)
print("ms1:", ms1)

print("Двумерный массив", ms2.dtype)
print("ms2 shape:", ms2.shape)
print("ms2:", ms2)

z = np.zeros((3,2))
o = np.ones((4,5))
psl = np.arange(5,30,7)
print("Массив из 0 ",z)
print("Массив из 1 ",o)
print("Последовательный массив от 5 до 30 с шагом 7",psl)

print("5й элемент масива ms1",ms1[4])
print("3-6 элементы масива ms1",ms1[2:7])

print("4й элмент 2й строки массива ms2",ms2[1,3])
print("1е элменты 1й и 2й строк массива ms2",ms2[[0,1],0])

ns1 = [10,20,30,40,50,60]
print("Поэлементное сложение массивов ms1 и ns1",ms1 + ns1)
ns2 = ms2.copy()
print("Поэлементное умножение массивов ms2 и ns2",ms2 * ns2)
print("Среднее значение массивов ms1 и ms2",ms1.mean(),ms2.mean())
print("Стандартное отклонение массивов ms1 и ms2",ms1.std(),ms2.std())

Одномерный массив int64
ms1 shape: (6,)
ms1: [1 2 3 4 5 6]
Двумерный массив int64
ms2 shape: (2, 4)
ms2: [[1 2 3 4]
 [5 6 7 8]]
Массив из 0  [[0. 0.]
 [0. 0.]
 [0. 0.]]
Массив из 1  [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Последовательный массив от 5 до 30 с шагом 7 [ 5 12 19 26]
5й элемент масива ms1 5
3-6 элементы масива ms1 [3 4 5 6]
4й элмент 2й строки массива ms2 8
1е элменты 1й и 2й строк массива ms2 [1 5]
Поэлементное сложение массивов ms1 и ns1 [11 22 33 44 55 66]
Поэлементное умножение массивов ms2 и ns2 [[ 1  4  9 16]
 [25 36 49 64]]
Среднее значение массивов ms1 и ms2 3.5 4.5
Стандартное отклонение массивов ms1 и ms2 1.707825127659933 2.29128784747792
